import type { RegistryManifest, Registry } from './types';

// Domain registries imports
import {
  serviceTypeRegistry,
  packageTypeRegistry,
  carrierRegistry,
  shippingMethodRegistry,
  shipmentStatusRegistry,
  shipmentPriorityRegistry,
  shipmentStageRegistry,
  deliveryOptionRegistry,
  deliveryAttemptRegistry,
  returnReasonRegistry,
} from './coreShipping';

import {
  labelTemplateRegistry,
  documentTypeRegistry,
  invoiceRegistry,
  packingSlipRegistry,
  manifestRegistry,
  customsDocumentRegistry,
  proofOfDeliveryRegistry,
  exportDocumentRegistry,
} from './documents';

import {
  packagingMaterialRegistry,
  boxSizeRegistry,
  dimensionPresetRegistry,
  weightClassRegistry,
  unitRegistry,
  hazardousMaterialRegistry,
  fragileHandlingRegistry,
} from './packaging';

import {
  printProfileRegistry,
  paperRegistry,
  labelSizeRegistry,
  printerRegistry,
  thermalPrinterRegistry,
  barcodeRegistry,
  qrRegistry,
  watermarkRegistry,
} from './print';

import {
  warehouseRegistry,
  distributionCenterRegistry,
  pickupLocationRegistry,
  dropoffLocationRegistry,
  routeRegistry,
  zoneRegistry,
  transitHubRegistry,
} from './logistics';

import {
  countryRegistry,
  stateRegistry,
  cityRegistry,
  postalCodeRegistry,
  currencyRegistry,
  languageRegistry,
  timezoneRegistry,
} from './geography';

import {
  paymentMethodRegistry,
  codRegistry,
  taxRegistry,
  gstRegistry,
  incotermRegistry,
  insuranceRegistry,
} from './payments';

import {
  addressBookRegistry,
  customerRegistry,
  supplierRegistry,
  vendorRegistry,
  organizationRegistry,
} from './customer';

import {
  workflowRegistry,
  actionRegistry,
  ruleRegistry,
  automationRegistry,
  notificationRegistry,
  approvalRegistry,
  permissionRegistry,
  auditRegistry,
} from './workflow';

import {
  uiLayoutRegistry,
  themeRegistry,
  iconRegistry,
  colorRegistry,
  typographyRegistry,
  animationRegistry,
} from './ui';

import {
  aiPromptRegistry,
  aiActionRegistry,
  aiAgentRegistry,
  aiWorkflowRegistry,
  aiValidationRegistry,
} from './ai';

import {
  validationRegistry,
  variableRegistry,
  expressionRegistry,
  formulaRegistry,
  schemaRegistry,
  metadataRegistry,
} from './metadata';

import { fieldRegistry } from './fieldRegistry';
import { sectionRegistry } from './sectionRegistry';

export const Manifest: RegistryManifest = {
  name: 'VONIXX Logistics Operating System Metadata Schema Registry',
  version: '3.0.0',
  registries: [
    { id: 'field-registry', namespace: 'vonixx.fields', version: '1.0.0' },
    { id: 'section-registry', namespace: 'vonixx.sections', version: '1.0.0' },
    { id: 'service-type-registry', namespace: 'vonixx.services', version: '1.0.0' },
    { id: 'package-type-registry', namespace: 'vonixx.packages', version: '1.0.0' },
    { id: 'carrier-registry', namespace: 'vonixx.carriers', version: '1.0.0' },
    { id: 'shipping-method-registry', namespace: 'vonixx.shipping-methods', version: '1.0.0' },
    { id: 'shipment-status-registry', namespace: 'vonixx.shipment-statuses', version: '1.0.0' },
    { id: 'shipment-priority-registry', namespace: 'vonixx.shipment-priorities', version: '1.0.0' },
    { id: 'shipment-stage-registry', namespace: 'vonixx.shipment-stages', version: '1.0.0' },
    { id: 'delivery-option-registry', namespace: 'vonixx.delivery-options', version: '1.0.0' },
    { id: 'delivery-attempt-registry', namespace: 'vonixx.delivery-attempts', version: '1.0.0' },
    { id: 'return-reason-registry', namespace: 'vonixx.return-reasons', version: '1.0.0' },
    { id: 'label-template-registry', namespace: 'vonixx.templates', version: '1.0.0' },
    { id: 'document-type-registry', namespace: 'vonixx.document-types', version: '1.0.0' },
    { id: 'invoice-registry', namespace: 'vonixx.invoices', version: '1.0.0' },
    { id: 'packing-slip-registry', namespace: 'vonixx.packing-slips', version: '1.0.0' },
    { id: 'manifest-registry', namespace: 'vonixx.manifests', version: '1.0.0' },
    { id: 'customs-document-registry', namespace: 'vonixx.customs', version: '1.0.0' },
    { id: 'proof-of-delivery-registry', namespace: 'vonixx.pod', version: '1.0.0' },
    { id: 'export-document-registry', namespace: 'vonixx.export-docs', version: '1.0.0' },
    { id: 'packaging-material-registry', namespace: 'vonixx.materials', version: '1.0.0' },
    { id: 'box-size-registry', namespace: 'vonixx.box-sizes', version: '1.0.0' },
    { id: 'dimension-preset-registry', namespace: 'vonixx.dimension-presets', version: '1.0.0' },
    { id: 'weight-class-registry', namespace: 'vonixx.weight-classes', version: '1.0.0' },
    { id: 'unit-registry', namespace: 'vonixx.units', version: '1.0.0' },
    { id: 'hazardous-material-registry', namespace: 'vonixx.hazmat', version: '1.0.0' },
    { id: 'fragile-handling-registry', namespace: 'vonixx.fragile-handling', version: '1.0.0' },
    { id: 'print-profile-registry', namespace: 'vonixx.print-profiles', version: '1.0.0' },
    { id: 'paper-registry', namespace: 'vonixx.papers', version: '1.0.0' },
    { id: 'label-size-registry', namespace: 'vonixx.layouts', version: '1.0.0' },
    { id: 'printer-registry', namespace: 'vonixx.printers', version: '1.0.0' },
    { id: 'thermal-printer-registry', namespace: 'vonixx.thermal-printers', version: '1.0.0' },
    { id: 'barcode-registry', namespace: 'vonixx.barcodes', version: '1.0.0' },
    { id: 'qr-registry', namespace: 'vonixx.qrs', version: '1.0.0' },
    { id: 'watermark-registry', namespace: 'vonixx.watermarks', version: '1.0.0' },
    { id: 'warehouse-registry', namespace: 'vonixx.warehouses', version: '1.0.0' },
    { id: 'distribution-center-registry', namespace: 'vonixx.dc', version: '1.0.0' },
    { id: 'pickup-location-registry', namespace: 'vonixx.pickup-locations', version: '1.0.0' },
    { id: 'dropoff-location-registry', namespace: 'vonixx.dropoff-locations', version: '1.0.0' },
    { id: 'route-registry', namespace: 'vonixx.routes', version: '1.0.0' },
    { id: 'zone-registry', namespace: 'vonixx.zones', version: '1.0.0' },
    { id: 'transit-hub-registry', namespace: 'vonixx.transit-hubs', version: '1.0.0' },
    { id: 'country-registry', namespace: 'vonixx.countries', version: '1.0.0' },
    { id: 'state-registry', namespace: 'vonixx.states', version: '1.0.0' },
    { id: 'city-registry', namespace: 'vonixx.cities', version: '1.0.0' },
    { id: 'postal-code-registry', namespace: 'vonixx.postal-codes', version: '1.0.0' },
    { id: 'currency-registry', namespace: 'vonixx.currencies', version: '1.0.0' },
    { id: 'language-registry', namespace: 'vonixx.languages', version: '1.0.0' },
    { id: 'timezone-registry', namespace: 'vonixx.timezones', version: '1.0.0' },
    { id: 'payment-method-registry', namespace: 'vonixx.payment-methods', version: '1.0.0' },
    { id: 'cod-registry', namespace: 'vonixx.cod', version: '1.0.0' },
    { id: 'tax-registry', namespace: 'vonixx.taxes', version: '1.0.0' },
    { id: 'gst-registry', namespace: 'vonixx.gst', version: '1.0.0' },
    { id: 'incoterm-registry', namespace: 'vonixx.incoterms', version: '1.0.0' },
    { id: 'insurance-registry', namespace: 'vonixx.insurance', version: '1.0.0' },
    { id: 'address-book-registry', namespace: 'vonixx.addresses', version: '1.0.0' },
    { id: 'customer-registry', namespace: 'vonixx.customers', version: '1.0.0' },
    { id: 'supplier-registry', namespace: 'vonixx.suppliers', version: '1.0.0' },
    { id: 'vendor-registry', namespace: 'vonixx.vendors', version: '1.0.0' },
    { id: 'organization-registry', namespace: 'vonixx.organizations', version: '1.0.0' },
    { id: 'workflow-registry', namespace: 'vonixx.workflows', version: '1.0.0' },
    { id: 'action-registry', namespace: 'vonixx.actions', version: '1.0.0' },
    { id: 'rule-registry', namespace: 'vonixx.rules', version: '1.0.0' },
    { id: 'automation-registry', namespace: 'vonixx.automations', version: '1.0.0' },
    { id: 'notification-registry', namespace: 'vonixx.notifications', version: '1.0.0' },
    { id: 'approval-registry', namespace: 'vonixx.approvals', version: '1.0.0' },
    { id: 'permission-registry', namespace: 'vonixx.permissions', version: '1.0.0' },
    { id: 'audit-registry', namespace: 'vonixx.audit', version: '1.0.0' },
    { id: 'ui-layout-registry', namespace: 'vonixx.ui-layouts', version: '1.0.0' },
    { id: 'theme-registry', namespace: 'vonixx.themes', version: '1.0.0' },
    { id: 'icon-registry', namespace: 'vonixx.icons', version: '1.0.0' },
    { id: 'color-registry', namespace: 'vonixx.colors', version: '1.0.0' },
    { id: 'typography-registry', namespace: 'vonixx.typography', version: '1.0.0' },
    { id: 'animation-registry', namespace: 'vonixx.animations', version: '1.0.0' },
    { id: 'ai-prompt-registry', namespace: 'vonixx.ai-prompts', version: '1.0.0' },
    { id: 'ai-action-registry', namespace: 'vonixx.ai-actions', version: '1.0.0' },
    { id: 'ai-agent-registry', namespace: 'vonixx.ai-agents', version: '1.0.0' },
    { id: 'ai-workflow-registry', namespace: 'vonixx.ai-workflows', version: '1.0.0' },
    { id: 'ai-validation-registry', namespace: 'vonixx.ai-validation', version: '1.0.0' },
    { id: 'validation-registry', namespace: 'vonixx.validation', version: '1.0.0' },
    { id: 'variable-registry', namespace: 'vonixx.variables', version: '1.0.0' },
    { id: 'expression-registry', namespace: 'vonixx.expressions', version: '1.0.0' },
    { id: 'formula-registry', namespace: 'vonixx.formulas', version: '1.0.0' },
    { id: 'schema-registry', namespace: 'vonixx.schemas', version: '1.0.0' },
    { id: 'metadata-registry', namespace: 'vonixx.metadata', version: '1.0.0' },
  ],
};

export const staticRegistryMap: Record<string, Registry<any>> = {
  'vonixx.fields': fieldRegistry,
  'vonixx.sections': sectionRegistry,
  'vonixx.services': serviceTypeRegistry,
  'vonixx.packages': packageTypeRegistry,
  'vonixx.carriers': carrierRegistry,
  'vonixx.shipping-methods': shippingMethodRegistry,
  'vonixx.shipment-statuses': shipmentStatusRegistry,
  'vonixx.shipment-priorities': shipmentPriorityRegistry,
  'vonixx.shipment-stages': shipmentStageRegistry,
  'vonixx.delivery-options': deliveryOptionRegistry,
  'vonixx.delivery-attempts': deliveryAttemptRegistry,
  'vonixx.return-reasons': returnReasonRegistry,
  'vonixx.templates': labelTemplateRegistry,
  'vonixx.document-types': documentTypeRegistry,
  'vonixx.invoices': invoiceRegistry,
  'vonixx.packing-slips': packingSlipRegistry,
  'vonixx.manifests': manifestRegistry,
  'vonixx.customs': customsDocumentRegistry,
  'vonixx.pod': proofOfDeliveryRegistry,
  'vonixx.export-docs': exportDocumentRegistry,
  'vonixx.materials': packagingMaterialRegistry,
  'vonixx.box-sizes': boxSizeRegistry,
  'vonixx.dimension-presets': dimensionPresetRegistry,
  'vonixx.weight-classes': weightClassRegistry,
  'vonixx.units': unitRegistry,
  'vonixx.hazmat': hazardousMaterialRegistry,
  'vonixx.fragile-handling': fragileHandlingRegistry,
  'vonixx.print-profiles': printProfileRegistry,
  'vonixx.papers': paperRegistry,
  'vonixx.layouts': labelSizeRegistry,
  'vonixx.printers': printerRegistry,
  'vonixx.thermal-printers': thermalPrinterRegistry,
  'vonixx.barcodes': barcodeRegistry,
  'vonixx.qrs': qrRegistry,
  'vonixx.watermarks': watermarkRegistry,
  'vonixx.warehouses': warehouseRegistry,
  'vonixx.dc': distributionCenterRegistry,
  'vonixx.pickup-locations': pickupLocationRegistry,
  'vonixx.dropoff-locations': dropoffLocationRegistry,
  'vonixx.routes': routeRegistry,
  'vonixx.zones': zoneRegistry,
  'vonixx.transit-hubs': transitHubRegistry,
  'vonixx.countries': countryRegistry,
  'vonixx.states': stateRegistry,
  'vonixx.cities': cityRegistry,
  'vonixx.postal-codes': postalCodeRegistry,
  'vonixx.currencies': currencyRegistry,
  'vonixx.languages': languageRegistry,
  'vonixx.timezones': timezoneRegistry,
  'vonixx.payment-methods': paymentMethodRegistry,
  'vonixx.cod': codRegistry,
  'vonixx.taxes': taxRegistry,
  'vonixx.gst': gstRegistry,
  'vonixx.incoterms': incotermRegistry,
  'vonixx.insurance': insuranceRegistry,
  'vonixx.addresses': addressBookRegistry,
  'vonixx.customers': customerRegistry,
  'vonixx.suppliers': supplierRegistry,
  'vonixx.vendors': vendorRegistry,
  'vonixx.organizations': organizationRegistry,
  'vonixx.workflows': workflowRegistry,
  'vonixx.actions': actionRegistry,
  'vonixx.rules': ruleRegistry,
  'vonixx.automations': automationRegistry,
  'vonixx.notifications': notificationRegistry,
  'vonixx.approvals': approvalRegistry,
  'vonixx.permissions': permissionRegistry,
  'vonixx.audit': auditRegistry,
  'vonixx.ui-layouts': uiLayoutRegistry,
  'vonixx.themes': themeRegistry,
  'vonixx.icons': iconRegistry,
  'vonixx.colors': colorRegistry,
  'vonixx.typography': typographyRegistry,
  'vonixx.animations': animationRegistry,
  'vonixx.ai-prompts': aiPromptRegistry,
  'vonixx.ai-actions': aiActionRegistry,
  'vonixx.ai-agents': aiAgentRegistry,
  'vonixx.ai-workflows': aiWorkflowRegistry,
  'vonixx.ai-validation': aiValidationRegistry,
  'vonixx.validation': validationRegistry,
  'vonixx.variables': variableRegistry,
  'vonixx.expressions': expressionRegistry,
  'vonixx.formulas': formulaRegistry,
  'vonixx.schemas': schemaRegistry,
  'vonixx.metadata': metadataRegistry,
};
